### PR TITLE
Fix #493: Ignore leading/trailing spaces in url

### LINKED ISSUE #493: Spaces before and after project URL should be ignored
For example:
`https://scratch.mit.edu/projects/313916295    `
is considered an invalid URL.

`src/internal/projecturl.cpp` is the file which controls this.

### PR DESCRIPTION
**Pull request by Jessie-JY2728**
Resolves #493.

### CODE REVIEW

**Comment by adazem009** [comment]
Thanks for your contribution. There seems to be an issue with these changes. According to unit tests, this URL isn't parsed correctly: `/scratch.mit.edu/projects/886166351`
`isProjectUrl()` should return true, but returns false.

**Comment by adazem009** [comment]
I think it would be much better to use `std::isspace()` to check for whitespace characters. For example check out these functions: https://github.com/musescore/MuseScore/blob/402fe051416bf4bc9d640ce0578603af3b07aefd/src/framework/global/stringutils.cpp#L65-L77

**Comment by Jessie-JY2728** [comment]
Thank you for you suggestion. Could you explain why the url should be valid? I guess it means the http is not required, is it? Also, I see there's a unit test configured, could you tell me how to run the tests locally?

**Comment by adazem009** [comment]
> Thank you for you suggestion. Could you explain why the url should be valid? I guess it means the http is not required, is it? And it failed because the first part is empty. Also, could you give instructions how to run unit tests locally?

Yes, `https://` isn't needed and it should be completely trimmed even if there's only `/`. To run unit tests locally, you can run `ctest -j$(nproc --all)` from the build directory. Or maybe your IDE has an option for it.

You can also add a test for this issue if you want. It's in the `test/network/projecturl_test.cpp` file.

**Comment by Jessie-JY2728** [comment]
It is so nice working with you :) I have also configured github action on my forked repo, and my 3rd commit has passed the unit test over there

**Comment by adazem009** [comment]
> It is so nice working with you :) I have also configured github action on my forked repo, and my 3rd commit has passed the unit test over there

Actually, unit tests are supposed to run in the pull request. There's no need to create a GitHub action in the forked repository. The problem is that I have to approve the checks manually before they run in the pull request. Maybe I should disable that...

By the way, do you also want to add a test for these changes or should I do it after merging the PR?

**Comment by adazem009** [comment]
Just a small detail. The newline at line 64 in projecturl.cpp shouldn't be there and was probably added by accident. Otherwise everything looks good.

**Comment by adazem009** [comment]
> > Just a small detail. The newline at line 68 in projecturl.cpp shouldn't be there and was probably added by accident. Besides that everything looks good.
> 
> Error: There's no line 68 in that file. Do you mean: 64? Removed. The newline at 63 was already there.

Yes, I meant 64, that was probably a typo.

**Review by adazem009 — APPROVED** [review]

**Pull request merged**
